2.2
mesonbuild/tinyply pull request #8
Opened 2018-08-16 19:38 UTC by barcharcraz

2018-08-17 13:16 UTC, sarum9in commented
Doesn't build, could you please take a look what's wrong?

$ mesonwrap review tinyply --pull_request=8
Inspecting project tinyply, branch 2.2.
Repo name valid: ☑
Branch name valid: ☑
Target branch is not master: ☑
Has readme.txt: ☑
Has LICENSE.build: ☑
Has upstream.wrap: ☑
Has toplevel meson.build: ☑
Repo contains only buildsystem files: ☑
upstream.wrap has directory: ☑
upstream.wrap directory has no path separators: ☑
upstream.wrap has source_url: ☑
upstream.wrap has source_filename: ☑
upstream.wrap source_filename has no path separators: ☑
upstream.wrap has source_hash: ☑
Download url works: ☑
Hash matches: ☑
upstream.wrap directory 'tinyply-2.2' exists: ☑
Patch merges with source: ☑
```The Meson build system
Version: 0.46.0.dev1
Source dir: /tmp/tmpl9ncsuc9/src/tinyply-2.2
Build dir: /tmp/tmpl9ncsuc9/bin
Build type: native build
Project name: tinyply
Native C++ compiler: c++ (gcc 8.1.1 "c++ (GCC) 8.1.1 20180531")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
meson setup: ☑
ninja: Entering directory `/tmp/tmpl9ncsuc9/bin'
[1/3] Compiling C++ object 'tinyply@sha/source_tinyply.cpp.o'.
FAILED: tinyply@sha/source_tinyply.cpp.o 
c++ -Itinyply@sha -I. -I../src/tinyply-2.2 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -fPIC  -MD -MQ 'tinyply@sha/source_tinyply.cpp.o' -MF 'tinyply@sha/source_tinyply.cpp.o.d' -o 'tinyply@sha/source_tinyply.cpp.o' -c ../src/tinyply-2.2/source/tinyply.cpp
../src/tinyply-2.2/source/tinyply.cpp:5:10: fatal error: tinyply.h: No such file or directory
 #include <tinyply.h>
          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
ninja test: ☒

2018-08-20 15:32 UTC, sarum9in requested changes
Good overall, minor fix requested.

2018-08-20 15:32 UTC, sarum9in commented on meson.build
> +		      include_directories: i,
Please use consistent indentation with spaces.

2018-08-26 21:27 UTC, barcharcraz commented
I think I’ve resolved the issues

2018-08-27 20:00 UTC, merged